spring:
  application:
    name: edamicrokafka-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/customers/**
        - id: login-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/logins/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8083

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
