spring:
  application:
    name: edamicrokafka-gateway

zuul:
  routes:
    customer-service:
      path: /api/customers/**
      url: http://localhost:8080
      stripPrefix: false
    login-service:
      path: /api/logins/**
      url: http://localhost:8081
      stripPrefix: false
    order-service:
      path: /api/orders/**
      url: http://localhost:8082
      stripPrefix: false
  ignored-services: "*"
  add-proxy-headers: true
  sensitive-headers: Cookie,Set-Cookie

server:
  port: 8083

logging:
  level:
    com.netflix.zuul: DEBUG
